version: "3.8"
services:
  gotify:
    image: gotify/server:2.4.0
    ports:
      - "8008:80"
    environment:
      GOTIFY_DEFAULTUSER_NAME: ${GOTIFY_DEFAULTUSER_NAME:-admin}
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS:-admin}
    volumes:
      - ./gotify-data:/app/data
    restart: unless-stopped
